version: '3.4'

services:
  pdsasm1:
    image: pdsasm1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 pds_asm1_main.py "]
    ports:
      - 5678:5678
