---
title: "AR/VR Data Analysis and Communication G (11524)"
subtitle: Final Test
author: ""
date: "Semester 2 2021"
output:
  pdf_document:
    highlight: breezedark
    df_print: kable
---

```{r include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# **Topic 3 – Data Visualisation and Communication.**
```{r include = FALSE}
require(tidyverse)
require(ggplot2)
```

## Q10
```{r}
data <- tibble(
  DATE = c(
    "2019-04",
    "2019-05",
    "2019-06",
    "2019-07",
    "2019-08",
    "2019-09",
    "2019-10",
    "2019-11",
    "2019-12",
    "2020-01",
    "2020-02",
    "2020-03"
  ),
  CAPACITY = c(
    29263,
    28037,
    21596,
    25895,
    25813,
    22427,
    23605,
    24263,
    24243,
    25533,
    24467,
    25194
  ),
  DEMAND = c(
    46193,
    49131,
    50124,
    48850,
    47602,
    43697,
    41058,
    37364,
    34364,
    34149,
    25573,
    25284
  )
)

glimpse(data)
```
### c)
```{r}
data %>%
  gather("KEY", "VALUE", -DATE) %>%
    ggplot(aes(DATE, VALUE, fill = KEY)) +
      geom_col(position = "dodge") +
      geom_smooth(aes(DATE, VALUE, group = KEY, color = KEY)) +
      ggtitle("Trend of Demand and Capacity") +
      theme(legend.title = element_blank()) +
      theme_minimal() +
      theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
      xlab("time (year-month)") +
      ylab("number of project hours")
```
